image: Visual Studio 2017
environment:
  DOTNET_CLI_TELEMETRY_OPTOUT: true
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
install:
  - cd src/BackEnd/
matrix:
  fast_finish: true
build: off
shallow_clone: true
test_script:
  - dotnet restore
  - dotnet build