# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

pool:
  vmImage: 'Ubuntu-16.04'

variables:
  buildConfiguration: 'Release'

steps:
- task: DotNetCoreInstaller@0
  inputs:
    version: '2.2.100'

- task: DotNetCoreCLI@2
  inputs:
    command: restore
    projects: 'src/BackEnd'

- script: dotnet build src/BackEnd/DevSocial.sln
  displayName: 'dotnet build $(buildConfiguration)'
